// src/components/timeline/timeline.tsx
"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import styles from "./timeline.module.sass";
import {projectDictionary} from "@/utils/project";
import Image from "next/image";

const BASE_URL = "https://raw.githubusercontent.com/jackgraddon/";

interface TimelineProps {
  projects: string[]; // Pass in your timelineProjects
}

interface ProjectDetails {
  id: string;
  name: string;
  description: string;
  url: string;
  backgroundColor: string;
  buttonColor: string;
  status: string;
}

export default function Timeline({ projects }: TimelineProps) {
  const [projectData, setProjectData] = useState<ProjectDetails[]>([]);

  const fetchProjectDetails = async (id: string): Promise<ProjectDetails | null> => {
    const repo = projectDictionary[id];
    if (!repo) {
      console.error(`Project ID ${id} not found in dictionary.`);
      return null;
    }
    const url = `${BASE_URL}${repo.url}`;
    try {
      const response = await fetch(url);
      if (!response.ok) {
        throw new Error(`Failed to fetch details for project ID ${id}: ${response.statusText}`);
      }
      return await response.json();
    } catch (error) {
      console.error(error);
      return null;
    }
  };

  useEffect(() => {
    const fetchAllProjects = async () => {
      const fetchedData = await Promise.all(projects.map(fetchProjectDetails));
      setProjectData(fetchedData.filter((data): data is ProjectDetails => data !== null)); // Filter out nulls
    };

    fetchAllProjects();
  }, [projects]);

  return (
    <div className={styles.timeline}>
      {projectData.map((project) => (
        <div key={project.id} className={styles["timeline-item"]}>
          <div
            className={styles["timeline-icon"]}
            style={{color: project.buttonColor}}
          >
            {`${project.id.slice(2, 4)}/${project.id.slice(0, 2)}`} {/* Convert to MM/YY format */}
          </div>
          <div
            key={project.id}
            className={styles.tile}
            style={{backgroundColor: project.backgroundColor}}
          >
            <Image
              src={`https://raw.githubusercontent.com/jackgraddon/${project.url.replace('/README.md', '/.projectDetails/ogImage.jpg')}`}
              alt={project.name}
              width={400}
              height={300}
              style={{objectFit: 'cover'}}
            />
            <Link
              className="btn"
              href={`/project?id=${project.id}`}
              style={{color: project.buttonColor}}
            >
              {project.name}
            </Link>
          </div>
        </div>
      ))}
    </div>
  );
}

// components/Timeline.vue
<template>
  <div :class="$style.timeline">
    <div 
      v-for="project in projectData" 
      :key="project.id" 
      :class="$style['timeline-item']"
    >
      <div
        :class="$style['timeline-icon']"
        :style="{ color: project.buttonColor }"
      >
        {{ `${project.id.slice(2, 4)}/${project.id.slice(0, 2)}` }}
      </div>
      <div
        :class="$style.tile"
        :style="{ backgroundColor: project.backgroundColor }"
      >
        <NuxtImg
          :src="`https://raw.githubusercontent.com/jackgraddon/${project.url.replace('/README.md', '/.projectDetails/ogImage.jpg')}`"
          :alt="project.name"
          width="400"
          height="300"
          style="object-fit: cover"
        />
        <NuxtLink
          class="btn"
          :to="`/project?id=${project.id}`"
          :style="{ color: project.buttonColor }"
        >
          {{ project.name }}
        </NuxtLink>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { projectDictionary } from '~/composables/project'

const BASE_URL = "https://raw.githubusercontent.com/jackgraddon/"

interface TimelineProps {
  projects: string[]
}

interface ProjectDetails {
  id: string
  name: string
  description: string
  url: string
  backgroundColor: string
  buttonColor: string
  status: string
}

const props = defineProps<TimelineProps>()

const projectData = ref<ProjectDetails[]>([])

const fetchProjectDetails = async (id: string): Promise<ProjectDetails | null> => {
  const repo = projectDictionary[id]
  if (!repo) {
    console.error(`Project ID ${id} not found in dictionary.`)
    return null
  }
  const url = `${BASE_URL}${repo.url}`
  try {
    const response = await fetch(url)
    if (!response.ok) {
      throw new Error(`Failed to fetch details for project ID ${id}: ${response.statusText}`)
    }
    return await response.json()
  } catch (error) {
    console.error(error)
    return null
  }
}

onMounted(async () => {
  const fetchedData = await Promise.all(props.projects.map(fetchProjectDetails))
  projectData.value = fetchedData.filter((data): data is ProjectDetails => data !== null)
})
</script>

<style module lang="sass">
.timeline
  display: flex
  flex-direction: column
  position: relative
  margin: 20px 0 0 420px
  padding: 0

  &::before
    background-color: #ccc
    width: 4px
    height: 100%
    content: ""
    position: absolute
    top: 0
    left: -2px
    border-radius: 7pt

  @media screen and (max-width: 768px), (orientation: portrait)
    width: 80%
    margin: 0
    gap: 0.5em

    &::before
      left: calc(50% - 2px)
      top: -10px
      height: calc(100% + 20px)

.timeline-item
  display: flex
  align-items: center
  margin: 20px 0
  position: relative

  @media screen and (max-width: 768px), (orientation: portrait)
    margin: 0
    width: 100%

  &:nth-child(even)
    flex-direction: row-reverse
    left: -100%

    .tile
      margin-left: 0
      margin-right: 60px

    @media screen and (max-width: 768px), (orientation: portrait)
      flex-direction: row
      left: 0

      .tile
        margin: 0

.timeline-icon
  background-color: white
  border: 0.3rem solid
  border-radius: 7pt
  width: fit-content
  height: 40px
  padding: 0.4rem 0.8rem
  display: flex
  justify-content: center
  align-items: center

  @media screen and (max-width: 768px), (orientation: portrait)
    margin: 0.5rem
    z-index: 1
    position: absolute
    top: 0
    left: 0

.tile
  margin-left: 60px
  margin-right: 0
  min-width: 300px
  max-height: 480px
  border-radius: 7pt
  aspect-ratio: 1.6
  overflow: hidden
  display: flex
  flex-flow: column
  justify-content: end
  align-items: flex-start
  position: relative

  @media screen and (max-width: 768px), (orientation: portrait)
    margin: 0
    width: 100%

  img
    width: 100%
    height: auto
    object-fit: cover
    position: absolute

  a
    margin: 0.5rem
    z-index: 1
</style>
